### ISSUE TITLE
No need for stereo

### ISSUE THREAD

**Issue by kaihendry** [revk/OpenMic#1]
Sidenote: Was going to email you but I can't find your email address anywhere.

https://youtu.be/mdEMZV1kZIc?t=247 is certainly interesting. I don't think you need stereo based on my recollection of watching:
https://youtu.be/3dQ6yKSttEc?t=1991

**Comment by revk** [comment]
Interesting, I'll have to experiment.

**Comment by revk** [comment]
OK I am not convinced, if you have good stereo microphones... https://youtu.be/DFdAWT_N13E

**Comment by kaihendry** [comment]
I struggled to hear the difference.
